services:
  app:
    build: .
    container_name: prediction-svc
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/prediction_svc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - prediction_network

  postgres:
    image: postgres:16-alpine
    container_name: prediction_svc_postgres
    environment:
      POSTGRES_DB: prediction_svc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prediction_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_prediction_svc
    restart: always
    ports:
      - "8888:80"
    networks:
      - prediction_network
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      - postgres

networks:
  prediction_network:
    driver: bridge

volumes:
  postgres_data: 